name: Unit Test BaudSniffer

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest]
        python-version: [
          '3.13.5', '3.12', '3.11', '3.10'
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyserial

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests